'use strict'

const projects = [
  { service: 'Google', pid: 1 },
  { service: 'Facebook', pid: 2 },
  { service: 'WhatsApp', pid: 3 },
  { service: 'LINE', pid: 4 },
  { service: 'Chatroulette', pid: 6 },
  { service: 'eBay', pid: 7 },
  { service: 'Instagram', pid: 8 },
  { service: 'BeeTalk', pid: 9 },
  { service: 'Telegram', pid: 10 },
  { service: 'Yahoo', pid: 15 },
  { service: 'VK.com Vkontakte English', pid: 17 },
  { service: 'Naver', pid: 18 },
  { service: 'Airbnb', pid: 19 },
  { service: 'freelancer', pid: 25 },
  { service: 'Webmoney', pid: 31 },
  { service: 'Tinder', pid: 51 },
  { service: 'Viber', pid: 55 },
  { service: 'Twitter (English)', pid: 66 },
  { service: '115.com', pid: 82 },
  { service: 'Azure', pid: 95 },
  { service: 'skype', pid: 114 },
  { service: 'Baidu', pid: 116 },
  { service: 'Uber', pid: 120 },
  { service: 'Astrill', pid: 140 },
  { service: 'Amazon', pid: 146 },
  { service: 'ICQ', pid: 210 },
  { service: 'APP.net', pid: 215 },
  { service: 'TALK2', pid: 225 },
  { service: 'Vine', pid: 232 },
  { service: 'KakaoTalk', pid: 245 },
  { service: 'Twilio', pid: 248 },
  { service: 'Badoo', pid: 283 },
  { service: 'snapchat', pid: 287 },
  { service: 'Weebly', pid: 297 },
  { service: 'OKru', pid: 331 },
  { service: '360 Cloud', pid: 337 },
  { service: 'Microsoft', pid: 338 },
  { service: 'Nvidia', pid: 341 },
  { service: 'SmartCall', pid: 342 },
  { service: 'MeetMe', pid: 344 },
  { service: 'PCGameSupply', pid: 345 },
  { service: 'Yandex.com', pid: 346 },
  { service: 'Vonage', pid: 347 },
  { service: 'GrabTaxi', pid: 349 },
  { service: 'Careem', pid: 352 },
  { service: 'NETEASE - 163', pid: 353 },
  { service: 'Sina Mail', pid: 354 },
  { service: 'BitGold', pid: 355 },
  { service: 'Fiverr', pid: 356 },
  { service: 'AOL', pid: 357 },
  { service: 'Playtoken(Chinese)', pid: 358 },
  { service: 'IMO', pid: 359 },
  { service: 'Baofeng Mojing', pid: 360 },
  { service: 'MOLO', pid: 361 },
  { service: 'Getresponse', pid: 362 },
  { service: 'Coins.ph', pid: 363 },
  { service: 'localbitcoins', pid: 364 },
  { service: 'Anyan', pid: 365 },
  { service: 'Weibo', pid: 366 },
  { service: 'ctyun', pid: 367 },
  { service: 'Turecaller', pid: 368 },
  { service: 'mhao.com', pid: 369 },
  { service: 'iSharkey', pid: 370 },
  { service: 'FreeBitco.in', pid: 371 },
  { service: 'Ticwatch', pid: 372 },
  { service: 'Baihe/百合网', pid: 373 },
  { service: 'Zhenai', pid: 374 },
  { service: 'Jiayuan', pid: 375 },
  { service: 'Coinbase', pid: 376 },
  { service: 'Circle', pid: 377 },
  { service: 'Mytaxi', pid: 379 },
  { service: 'EZVIZ - Chinese version', pid: 380 },
  { service: 'Tuandai', pid: 381 },
  { service: '少女前线', pid: 382 },
  { service: 'BAND.us', pid: 383 },
  { service: 'Zhenfu', pid: 384 },
  { service: 'dabtc', pid: 385 },
  { service: 'Alibaba', pid: 387 },
  { service: 'Carousell', pid: 388 },
  { service: 'Xiaomi', pid: 389 },
  { service: 'Lyft', pid: 390 },
  { service: 'zhgtrade.com', pid: 391 },
  { service: 'Youku', pid: 392 },
  { service: 'Bileyuan|币乐园', pid: 393 },
  { service: 'mmbang|妈妈帮', pid: 394 },
  { service: 'fetlife', pid: 395 },
  { service: 'Ninebot', pid: 396 },
  { service: 'IT168', pid: 397 },
  { service: 'Gameflip', pid: 398 },
  { service: 'Goluk', pid: 399 },
  { service: 'QQ', pid: 400 },
  { service: 'skout', pid: 401 },
  { service: 'SEAGM', pid: 402 },
  { service: 'Yuanbao', pid: 403 },
  { service: 'Protonmail', pid: 404 },
  { service: 'VENMO', pid: 405 },
  { service: '58.com', pid: 408 },
  { service: 'Wirex', pid: 409 },
  { service: 'Gett', pid: 411 },
  { service: 'jubi.com', pid: 412 },
  { service: 'zbj.com', pid: 413 },
  { service: 'yobtc', pid: 414 },
  { service: 'IT Pro Cloud', pid: 415 },
  { service: 'Wechat(Test before use)', pid: 416 },
  { service: 'Laohu.com', pid: 418 },
  { service: 'Epay', pid: 419 },
  { service: 'Bidvertiser', pid: 420 },
  { service: 'Panda.tv', pid: 421 },
  { service: 'Badoo Regsiter', pid: 422 },
  { service: '3721w.com', pid: 423 },
  { service: 'Listia', pid: 426 },
  { service: 'Steam', pid: 427 },
  { service: 'Skout', pid: 428 },
  { service: 'Purse.io', pid: 429 },
  { service: 'Uber English', pid: 430 },
  { service: 'Daum', pid: 432 },
  { service: 'Goldmoney', pid: 433 },
  { service: '酷划|Coohua', pid: 434 },
  { service: 'Rebtel', pid: 435 },
  { service: 'NobelApp', pid: 436 },
  { service: 'Mailgun', pid: 437 },
  { service: 'Stage1动漫游戏社区', pid: 438 },
  { service: 'Yandex.ru', pid: 439 },
  { service: '鑫币网|xinbi168.com', pid: 440 },
  { service: 'stellar', pid: 441 },
  { service: 'Huawei Wear', pid: 442 },
  { service: 'BTC100', pid: 443 },
  { service: 'Qiniu|七牛云', pid: 444 },
  { service: 'TCL|铁粉', pid: 445 },
  { service: 'zhiji|知己网', pid: 446 },
  { service: 'Letv|乐视', pid: 447 },
  { service: 'Flexiroam X', pid: 448 },
  { service: 'Advcash', pid: 449 },
  { service: 'Vipkid.com.cn', pid: 450 },
  { service: 'MTCGMAE', pid: 451 },
  { service: 'Hotcast.cn', pid: 452 },
  { service: 'Mymusictaste', pid: 453 },
  { service: 'Periscope', pid: 454 },
  { service: 'Lecheng', pid: 455 },
  { service: 'Youzu|游族', pid: 456 },
  { service: 'niu.com|小牛电动', pid: 457 },
  { service: 'uCoz', pid: 458 },
  { service: 'Nttgame', pid: 459 },
  { service: 'digits', pid: 460 },
  { service: 'Colu', pid: 461 },
  { service: 'Nike', pid: 462 },
  { service: 'chedingdong|车叮咚', pid: 463 },
  { service: 'Ximalaya|喜马拉雅电台', pid: 464 },
  { service: 'Zhekou5|昭诚', pid: 465 },
  { service: 'Fastmail', pid: 466 },
  { service: 'MapleStory2|冒险岛2', pid: 467 },
  { service: 'Uber eats', pid: 468 },
  { service: 'Craigslist(For USA)', pid: 469 },
  { service: 'Leupay', pid: 470 },
  { service: '星城online', pid: 471 },
  { service: 'Content.ad', pid: 472 },
  { service: 'FL.ru', pid: 473 },
  { service: '易介|yijie', pid: 474 },
  { service: 'Zoho', pid: 475 },
  { service: 'G2A', pid: 476 },
  { service: 'Epay', pid: 477 },
  { service: 'hwcloud|华为云', pid: 479 },
  { service: 'UR money', pid: 480 },
  { service: 'BuySomeBitcoins', pid: 481 },
  { service: '51job', pid: 482 },
  { service: 'Ninebot APP', pid: 483 },
  { service: 'RichmondBerks', pid: 484 },
  { service: 'Wire', pid: 485 },
  { service: 'flippa', pid: 486 },
  { service: 'ZoomInfo', pid: 487 },
  { service: 'Perfect World|完美世界', pid: 488 },
  { service: 'Mail.ru', pid: 489 },
  { service: 'PlayerAuctions', pid: 490 },
  { service: 'steemit', pid: 491 },
  { service: 'Affirm', pid: 492 },
  { service: 'Shopee', pid: 493 },
  { service: 'Oracle', pid: 494 },
  { service: 'zhan.com|小站', pid: 495 },
  { service: 'Zoosk', pid: 496 },
  { service: 'zen.ly', pid: 497 },
  { service: 'Bitekuang|比特矿', pid: 498 },
  { service: 'yes777.com.tw', pid: 499 },
  { service: 'Humblebundle', pid: 500 },
  { service: 'Musical.ly', pid: 501 },
  { service: '比特币交易网|btctrade.com', pid: 502 },
  { service: 'gatehub.net', pid: 503 },
  { service: 'Comfi', pid: 504 },
  { service: 'UnitedStack', pid: 505 },
  { service: 'foodpanda', pid: 506 },
  { service: 'ICOAGE', pid: 507 },
  { service: 'luno', pid: 508 },
  { service: 'Linkedin', pid: 509 },
  { service: 'call2friends', pid: 510 },
  { service: 'Shasso', pid: 511 },
  { service: 'OffGamers', pid: 512 },
  { service: 'Okpay', pid: 513 },
  { service: 'Streetbees', pid: 514 },
  { service: 'Office 365', pid: 515 },
  { service: 'foodora', pid: 516 },
  { service: 'thaifriendly', pid: 517 },
  { service: 'paxful', pid: 518 },
  { service: 'Primo', pid: 519 },
  { service: '音悦Tai|yinyuetai', pid: 520 },
  { service: 'YY.com', pid: 521 },
  { service: 'Cdkeys.com', pid: 522 },
  { service: 'CSDN.net', pid: 523 },
  { service: 'zhihu.com', pid: 524 },
  { service: '果盘游戏', pid: 525 },
  { service: 'Honestbee', pid: 526 },
  { service: 'Jiaoyou|中国交友网', pid: 527 },
  { service: 'GamaniaHK', pid: 528 },
  { service: '币久|BTC9', pid: 529 },
  { service: 'Livescore', pid: 530 },
  { service: 'ico365', pid: 531 },
  { service: '3ico', pid: 532 },
  { service: 'beico.io', pid: 533 },
  { service: 'Xunlei|迅雷', pid: 534 },
  { service: 'allcoin', pid: 535 },
  { service: '微软小冰', pid: 536 },
  { service: 'JD register|京东注册', pid: 537 },
  { service: 'btc100.com', pid: 538 },
  { service: '见见|91jianjian', pid: 539 },
  { service: '有缘|youyuan', pid: 540 },
  { service: '缘分|365yf.com', pid: 541 },
  { service: 'CheckPoints', pid: 542 },
  { service: 'simwe.com', pid: 543 },
  { service: 'Discord', pid: 544 },
  { service: 'Spotify', pid: 545 },
  { service: '慧博|hibor.com.cn', pid: 546 },
  { service: '巨人网络|ztgame.com', pid: 547 },
  { service: 'adidas', pid: 548 },
  { service: 'gfan.com', pid: 549 },
  { service: 'FAVE', pid: 550 },
  { service: 'Klook', pid: 551 },
  { service: 'VK.com Russia', pid: 552 },
  { service: 'Tiancity世纪天成', pid: 553 },
  { service: 'huomao|火猫', pid: 554 },
  { service: 'Authy', pid: 555 },
  { service: 'Ankama', pid: 556 },
  { service: 'Sonetel', pid: 557 },
  { service: 'Vmall|华为商城', pid: 558 },
  { service: 'Telz', pid: 559 },
  { service: 'zadarma', pid: 560 },
  { service: 'zalo.me', pid: 561 },
  { service: 'wacoin.io', pid: 562 },
  { service: 'travelmob', pid: 563 },
  { service: 'Signal.org', pid: 564 },
  { service: 'Bitmain比特大陆', pid: 565 },
  { service: '70mai|70迈', pid: 566 },
  { service: 'backpage', pid: 567 },
  { service: 'eefocus|与非网', pid: 568 },
  { service: 'HC360|慧聪网', pid: 569 },
  { service: 'yhd.com|一号店', pid: 570 },
  { service: 'Backblaze', pid: 571 },
  { service: 'Meme Live APP|么么直播', pid: 572 },
  { service: 'Bussinessstore Mircosoft', pid: 573 },
  { service: 'avis.cn', pid: 574 },
  { service: '5173.com', pid: 575 },
  { service: 'xcoins', pid: 576 },
  { service: 'coinmeet', pid: 577 },
  { service: 'SEMrush', pid: 578 },
  { service: 'xiangcloud象云', pid: 579 },
  { service: 'binance币安', pid: 580 },
  { service: 'Hushmail', pid: 581 },
  { service: 'LBANK.INFO', pid: 582 },
  { service: 'ymatou|洋码头', pid: 583 },
  { service: 'Kuaishou|快手', pid: 584 },
  { service: 'Huobi|火币', pid: 585 },
  { service: 'HQ trivia', pid: 586 },
  { service: 'wotb.163.com', pid: 587 },
  { service: 'moab.pro', pid: 588 },
  { service: 'coinw', pid: 589 },
  { service: '中信楷岚', pid: 590 },
  { service: 'LOVESTRUCK', pid: 591 },
  { service: 'Tantan|探探', pid: 592 },
  { service: 'Momo|陌陌', pid: 593 },
  { service: 'paktor', pid: 594 },
  { service: 'CenturyLink', pid: 595 },
  { service: '绝地求生', pid: 596 },
  { service: 'HB.TOP', pid: 597 },
  { service: 'Oracle', pid: 598 },
  { service: 'DateInAsia', pid: 599 },
  { service: 'ClickGem', pid: 600 },
  { service: 'DoorDash', pid: 602 },
  { service: 'Cash Show', pid: 603 },
  { service: 'Luna Node', pid: 604 },
  { service: 'z.com', pid: 605 },
  { service: 'coinbene', pid: 606 },
  { service: 'LBRY', pid: 607 },
  { service: 'Juno', pid: 608 },
  { service: 'Sohu', pid: 609 },
  { service: 'ooopic', pid: 610 },
  { service: 'JapanCodeSupply', pid: 611 },
  { service: 'dyson', pid: 612 },
  { service: 'douyin', pid: 613 },
  { service: 'douban', pid: 614 },
  { service: 'c5game', pid: 615 },
  { service: 'Rediffmail', pid: 616 },
  { service: 'Hupu|虎扑', pid: 617 },
  { service: 'dukascopy911', pid: 618 },
  { service: '露天拍賣', pid: 619 },
  { service: 'izhenxin爱真心', pid: 620 },
  { service: '蜗壳woker.cc', pid: 621 },
  { service: 'netflix', pid: 622 },
  { service: 'Revolut', pid: 623 },
  { service: 'electroneum', pid: 624 },
  { service: 'vivo', pid: 625 },
  { service: 'BIXIN比心', pid: 626 },
  { service: 'Telegram(New SIM)', pid: 627 },
  { service: 'Nike(New SIM)', pid: 628 },
  { service: 'Soroush', pid: 629 },
  { service: 'GG大玩家', pid: 631 },
  { service: 'LeaseVille', pid: 632 },
  { service: 'Nate', pid: 633 },
  { service: 'btok', pid: 634 },
  { service: 'Viberate', pid: 635 },
  { service: 'ClassPass', pid: 636 },
  { service: 'Duowan', pid: 637 },
  { service: 'GOFUNDME', pid: 638 },
  { service: 'oneplus|一加手机', pid: 639 },
  { service: 'CTRIP|携程', pid: 640 },
  { service: 'MUSDcoin', pid: 641 },
  { service: 'Sweatcoin', pid: 642 },
  { service: 'Sendgrid', pid: 643 },
  { service: 'Apple', pid: 644 },
  { service: 'epnex', pid: 645 },
  { service: 'Bumble', pid: 646 },
  { service: 'FacePoker', pid: 647 },
  { service: '部落先锋', pid: 648 },
  { service: '扑克王', pid: 649 },
  { service: '超级扑克', pid: 650 },
  { service: '王国游戏', pid: 651 },
  { service: '智玩竞技', pid: 652 },
  { service: 'Oh Poker', pid: 653 },
  { service: '触宝电话', pid: 654 },
  { service: '宝二爷令牌', pid: 655 },
  { service: 'Messenger', pid: 656 },
  { service: 'Razer Pay', pid: 657 },
  { service: 'Scaleway', pid: 658 },
  { service: 'OPPO', pid: 659 },
  { service: 'ylike|缘来客', pid: 660 },
  { service: 'hongniang|中国红娘', pid: 661 },
  { service: 'phicomm', pid: 662 }
]

exports.serviceToPID = { }
exports.pidToService = { }

projects.forEach((project) => {
  const service = project.service.toLowerCase().trim()
  const pid = project.pid

  exports.serviceToPID[service] = pid
  exports.pidToService[pid] = service
})
